name: "Sanity Check"

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v2

      - name: "Setup Environment"
        run: |
          git clone https://github.com/Scene-Collective/ps4-payload-sdk ~/ps4-payload-sdk && cd "$_"
          chmod +x install.sh
          sudo ./install.sh

      - name: "Build Payload"
        run: |
          export PS4SDK=/lib/ps4-payload-sdk
          make

      - name: "Upload Binary Artifact"
        uses: actions/upload-artifact@v4
        with:
          path: ./*.bin
          if-no-files-found: error
